name: Post every 24 hours

on:
#  schedule:
#    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: python

    - name: Download Image Log file
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: image_log
        path: ./python/image_log.txt
    
    - name: Run Python script
      run: python image_gen.py
      env:
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      working-directory: python

    - name: Upload Image Log file
      uses: actions/upload-artifact@v4
      with:
        name: image_log
        path: ./python/image_log.txt

    # TypeScript section
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install npm dependencies
      run: npm install
      working-directory: typescript
        
    - name: Compile TypeScript
      run: npm run build
      working-directory: typescript

    - name: Create post
      run: npm run start
      working-directory: typescript
      env:
        HANDLE: ${{ vars.HANDLE }}
        PASSWORD: ${{ secrets.PASSWORD }}

      


