name: Post every 24 hours

on:
#  schedule:
#    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-post:
    runs-on: ubuntu-latest

    env:
      HANDLE: ${{ vars.HANDLE }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: python

    - name: Download Image Log file
      uses: dawidd6/action-download-artifact@v3
      with:
        name: image_log
        path: ./python/
        if_no_artifact_found: warn
        search_artifacts: true
    
    - name: Run Python script
      run: python image_gen.py
      env:
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      working-directory: python

    - name: Upload Image Log file
      uses: actions/upload-artifact@v4
      with:
        name: image_log
        path: ./python/image_log.txt

    # TypeScript section
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install
      working-directory: typescript

    - name: Create post
      run: npm run start
      working-directory: typescript
